### ISSUE TITLE
Basic Usage Error

### ISSUE THREAD

**Issue by kzisme** [foresthoffman/bot#1]
`	myBot := Bot.BasicBot{
`

Should be

`	myBot := bot.BasicBot{
`

This can also be reflected in [doc.go](https://github.com/foresthoffman/bot/blob/master/doc.go)

**Comment by foresthoffman** [comment]
Should be fixed by [#920d879c](https://github.com/foresthoffman/bot/commit/920d879c34632d48749a01b68dc629ff97405681)
